---
# tasks file for roles/create-endpoint

- name: Create Service Project
  shell: . /root/.bashrc && openstack project create --domain default   --description "Service Project" service
#openstack service create --name glance  --description "OpenStack Image" image
#openstack service create --name placement  --description "Placement API" placement
#openstack service create --name nova  --description "OpenStack Compute" compute
#openstack service create --name neutron  --description "OpenStack Networking" network
#openstack service create --name cinderv2   --description "OpenStack Block Storage" volumev2
#openstack service create --name cinderv3   --description "OpenStack Block Storage" volumev3


- name: Create the glance user
  shell: . /root/.bashrc && openstack user create --domain default --password {{ GLANCE_PASS }} glance && openstack role add --project service --user glance admin
- name: Create the glance service
  shell: . /root/.bashrc && openstack service create --name glance  --description "OpenStack Image" image
- name: Create Image service API
  shell: . /root/.bashrc && openstack endpoint create --region RegionOne  image public http://{{ controller_ip }}:9292 && openstack endpoint create --region RegionOne   image internal http://{{ controller_ip }}:9292 && openstack endpoint create --region RegionOne   image admin http://{{ controller_ip }}:9292

- name: Create the placement user
  shell: . /root/.bashrc && openstack user create --domain default --password {{ PLACEMENT_PASS }} placement && openstack role add --project service --user placement admin
- name: Create the placement service
  shell: . /root/.bashrc && openstack service create --name placement  --description "Placement API" placement
- name: Create Placement endpoint API
  shell: . /root/.bashrc && openstack endpoint create --region RegionOne  placement public http://{{ controller_ip }}:8778 && openstack endpoint create --region RegionOne  placement internal http://{{ controller_ip }}:8778 && openstack endpoint create --region RegionOne  placement admin http://{{ controller_ip }}:8778

- name: Create the nova user
  shell:  . /root/.bashrc && openstack user create --domain default --password {{ NOVA_PASS }} nova && openstack role add --project service --user nova admin
- name: Create the nova service
  shell:  . /root/.bashrc && openstack service create --name nova  --description "OpenStack Compute" compute
- name: Create the Compute API service
  shell:  . /root/.bashrc && openstack endpoint create --region RegionOne  compute public http://{{ controller_ip }}:8774/v2.1 && openstack endpoint create --region RegionOne  compute internal http://{{ controller_ip }}:8774/v2.1 && openstack endpoint create --region RegionOne  compute admin http://{{ controller_ip }}:8774/v2.1

- name: Create the neutron user
  shell:  . /root/.bashrc && openstack user create --domain default --password {{ NEUTRON_PASS }} neutron && openstack role add --project service --user neutron admin
- name: Create neutron service
  shell: . /root/.bashrc && openstack service create --name neutron   --description "OpenStack Networking" network
- name: Create the Networking  API service  
  shell: . /root/.bashrc && openstack endpoint create --region RegionOne  network public http://{{ controller_ip }}:9696 && openstack endpoint create --region RegionOne  network internal http://{{ controller_ip }}:9696 && openstack endpoint create --region RegionOne  network admin http://{{ controller_ip }}:9696

- name: Create the cinder user
  shell:  . /root/.bashrc && openstack user create --domain default --password {{ CINDER_PASS }} cinder && openstack role add --project service --user cinder admin
- name: Create the cinderv2 and cinderv3
  shell:  . /root/.bashrc && openstack service create --name cinderv2  --description "OpenStack Block Storage" volumev2 && openstack service create --name cinderv3   --description "OpenStack Block Storage" volumev3
- name: Create the Block Storage service API Cinderv2
  shell: . /root/.bashrc && openstack endpoint create --region RegionOne  volumev2 public http://{{ controller_ip }}:8776/v2/%\(project_id\)s && openstack endpoint create --region RegionOne  volumev2 internal http://{{ controller_ip }}:8776/v2/%\(project_id\)s && openstack endpoint create --region RegionOne  volumev2 admin http://{{ controller_ip }}:8776/v2/%\(project_id\)s
- name: Create the Block Storage service API Cinderv3
  shell: . /root/.bashrc && openstack endpoint create --region RegionOne  volumev3 public http://{{ controller_ip }}:8776/v3/%\(project_id\)s && openstack endpoint create --region RegionOne  volumev3 internal http://{{ controller_ip }}:8776/v3/%\(project_id\)s && openstack endpoint create --region RegionOne  volumev3 admin http://{{ controller_ip }}:8776/v3/%\(project_id\)s
