---
# tasks file for roles/etcd
- name: Install etcd
  apt:
    name: etcd
- name: Config etcd
  template:
    src: etcd.j2
    dest: /etc/default/etcd
    mode: 0644
- name: Restart ETCD
  shell: systemctl restart etcd