---
# tasks file for roles/cinder-controller

- name: Install cinder
  apt:
    name: 
      - cinder-api
      - cinder-scheduler
- name: Config cinder
  template:
    src: cinder.conf.j2
    dest: /etc/cinder/cinder.conf
    mode: 0644
    owner: cinder
    group: cinder
- name: Populate the cinder-api database
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
- name: Restart service cinder
  shell: service nova-api restart && service cinder-scheduler restart && service apache2 restart