
- hosts: compute-1
  become: yes
  roles:
    - {role: environment, tags: environment}
    - {role: lvm-cinder, tags: lvm-cinder}
    - {role: nova-compute, tags: nova-compute}
    - {role: neutron-compute, tags: neutron-compute}
    - {role: cinder-node, tags: cinder-node}

