---
# tasks file for roles/create-databases
- name: Create the  database keystone
  command: mysql -u root --execute="CREATE DATABASE keystone;"
  ignore_errors: yes
- name: Grant proper access  to the keystone database
  command: mysql -u root  --execute="GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ KEYSTONE_DBPASS }}';GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ KEYSTONE_DBPASS }}';"

- name: Create the  database glance
  command: mysql -u root  --execute="CREATE DATABASE glance;"
  ignore_errors: yes
- name: Grant proper access  to the glance database
  command: mysql -u root  --execute="GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ GLANCE_DBPASS }}';GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ GLANCE_DBPASS }}';"
- name: Create the  database placement
  command: mysql -u root  --execute="CREATE DATABASE placement;"
  ignore_errors: yes
- name: Grant proper access  to the nova database
  command: mysql -u root  --execute="GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'localhost' IDENTIFIED BY '{{ PLACEMENT_DBPASS }}';GRANT ALL PRIVILEGES ON placement.* TO 'placement'@'%' IDENTIFIED BY '{{ PLACEMENT_DBPASS }}';"

- name: Create the  database nova
  command: mysql -u root  --execute="CREATE DATABASE nova_api;CREATE DATABASE nova;CREATE DATABASE nova_cell0;"
  ignore_errors: yes
- name: Grant proper access  to the nova database
  command: mysql -u root  --execute="  GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost'  IDENTIFIED BY '{{ NOVA_DBPASS }}';  GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%'   IDENTIFIED BY '{{ NOVA_DBPASS }}';   GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost'   IDENTIFIED BY '{{ NOVA_DBPASS }}';  GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%'   IDENTIFIED BY '{{ NOVA_DBPASS }}';  GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'localhost'   IDENTIFIED BY '{{ NOVA_DBPASS }}';  GRANT ALL PRIVILEGES ON nova_cell0.* TO 'nova'@'%'   IDENTIFIED BY '{{ NOVA_DBPASS }}';"

- name: Create the  database neutron
  command: mysql -u root  --execute="CREATE DATABASE neutron;"
  ignore_errors: yes
- name: Grant proper access  to the neutron database
  command: mysql -u root  --execute="GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ NEUTRON_DBPASS }}';GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ NEUTRON_DBPASS }}';"

- name: Create the  database cinder
  command: mysql -u root  --execute="CREATE DATABASE cinder;"
  ignore_errors: yes
- name: Grant proper access  to the cinder database
  command: mysql -u root  --execute="GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'localhost'  IDENTIFIED BY '{{ CINDER_DBPASS }}'; GRANT ALL PRIVILEGES ON cinder.* TO 'cinder'@'%'   IDENTIFIED BY '{{ CINDER_DBPASS }}';"

