---
# tasks file for roles/environment
- name: Install software-properties-common
  apt:
    name: software-properties-common
- name: Install Network Time Protocol
  apt:
    name: chrony
- name: Add-apt-repository Victoria
  shell: sudo add-apt-repository cloud-archive:victoria -y
- name: Install openstackclient
  apt:
    name: python3-openstackclient
  
